name: "Build Python Wheel"
description: "Runs the common steps to build the Python wheel"

inputs:
  runner-key:
    description: 'A unique key for the runner (e.g., matrix.os or "alpine")'
    required: true
  artifact-name:
    description: "The name for the upload-artifact step"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: uv sync --no-install-project
      shell: sh

    - name: Set path in environment
      run: echo "PROJECT_ROOT=${{ github.workspace }}" >> $GITHUB_ENV
      shell: sh

    - name: Cache Bindings
      id: cache-bindings
      uses: actions/cache@v4
      with:
        path: tree_sitter_language_pack/bindings
        key: ${{ inputs.runner-key }}-build-${{ hashFiles('sources/**/*', 'parsers/**/*', 'setup.py') }}

    - name: Build Extensions
      if: steps.cache-bindings.outputs.cache-hit != 'true'
      run: uv run setup.py build_ext --inplace
      shell: sh
      env:
        PROJECT_ROOT: ${{github.workspace}}

    - name: Build wheel
      run: |
        uv build --wheel
        echo "Built wheels:"
        ls -lh dist/*.whl || echo "No wheels found in dist/"
      shell: sh
      env:
        PROJECT_ROOT: ${{github.workspace}}

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        if-no-files-found: error
        path: dist
