name: "Test Python Wheel"
description: "Runs tests on a built Python wheel"

inputs:
  artifact-name:
    description: "The name of the wheel artifact to download and test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download wheel artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: Find and install wheel
      run: |
        # Try dist/*.whl first (standard location)
        wheel_file=$(ls dist/*.whl 2>/dev/null | head -n 1)
        # If not found, search recursively
        if [ -z "$wheel_file" ]; then
          wheel_file=$(find . -name "*.whl" -type f | head -n 1)
        fi
        if [ -z "$wheel_file" ]; then
          echo "ERROR: No wheel file found!"
          exit 1
        fi
        # Update pip to ensure musllinux tag support (PEP 656)
        pip install --upgrade pip
        # Install the wheel
        pip install "$wheel_file"
      shell: sh

    - name: Install pytest
      run: pip install pytest
      shell: sh

    - name: Test with installed wheel
      run: |
        mkdir -p /tmp/test_wheel
        cp tests/entry_point_test.py /tmp/test_wheel/
        cd /tmp/test_wheel
        pytest entry_point_test.py -v
      shell: sh
      env:
        PROJECT_ROOT: ${{ github.workspace }}
