from importlib import import_module
from typing import Callable, Literal, Union, cast

from tree_sitter import Language, Parser
from tree_sitter_c_sharp import language as c_sharp_language
from tree_sitter_embedded_template import language as embedded_template_language
from tree_sitter_yaml import language as yaml_language

InstalledBindings = Literal["csharp", "embeddedtemplate", "yaml"]
SupportedLanguage = Union[
    Literal[
        "actionscript",
        "ada",
        "agda",
        "arduino",
        "asm",
        "astro",
        "bash",
        "beancount",
        "bibtex",
        "bicep",
        "bitbake",
        "c",
        "cairo",
        "capnp",
        "chatito",
        "clarity",
        "clojure",
        "cmake",
        "comment",
        "commonlisp",
        "cpon",
        "cpp",
        "css",
        "csv",
        "cuda",
        "d",
        "dart",
        "dockerfile",
        "doxygen",
        "dtd",
        "elisp",
        "elixir",
        "elm",
        "erlang",
        "fennel",
        "firrtl",
        "fish",
        "fluent",
        "fortran",
        "func",
        "gdscript",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "gitrebase",
        "gleam",
        "glsl",
        "gn",
        "go",
        "gomod",
        "gosum",
        "groovy",
        "gstlaunch",
        "hack",
        "hare",
        "haskell",
        "haxe",
        "hcl",
        "heex",
        "hlsl",
        "html",
        "hyprlang",
        "ispc",
        "jai",
        "janetsimple",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "jsonnet",
        "julia",
        "kconfig",
        "kdl",
        "kotlin",
        "latex",
        "linkerscript",
        "llvm",
        "llvmmir",
        "lua",
        "luadoc",
        "luap",
        "luau",
        "magik",
        "make",
        "markdown",
        "matlab",
        "mermaid",
        "meson",
        "ninja",
        "nix",
        "noir",
        "nqc",
        "objc",
        "ocaml",
        "odin",
        "org",
        "pascal",
        "pem",
        "perl",
        "pgn",
        "php",
        "po",
        "pony",
        "powershell",
        "printf",
        "prisma",
        "properties",
        "psv",
        "puppet",
        "purescript",
        "pymanifest",
        "python",
        "qmldir",
        "qmljs",
        "query",
        "r",
        "racket",
        "re2c",
        "readline",
        "requirements",
        "ron",
        "rst",
        "ruby",
        "rust",
        "scala",
        "scheme",
        "scss",
        "smali",
        "smithy",
        "solidity",
        "sql",
        "squirrel",
        "starlark",
        "svelte",
        "swift",
        "tablegen",
        "tcl",
        "terraform",
        "test",
        "thrift",
        "toml",
        "tsv",
        "tsx",
        "twig",
        "typescript",
        "typst",
        "udev",
        "ungrammar",
        "uxntal",
        "v",
        "verilog",
        "vhdl",
        "vim",
        "vue",
        "wgsl",
        "xcompose",
        "xml",
        "yuck",
        "zig",
    ],
    InstalledBindings,
]

installed_bindings_map: dict[InstalledBindings, Callable[[], int]] = {
    "csharp": c_sharp_language,
    "embeddedtemplate": embedded_template_language,
    "yaml": yaml_language,
}


def get_language(language_name: SupportedLanguage) -> Language:
    """Get the language with the given name."""
    if language_name in installed_bindings_map:
        return Language(installed_bindings_map[cast(InstalledBindings, language_name)]())

    try:
        module = import_module(name=f".bindings.{language_name}", package=__package__)
        return Language(module.language())
    except ModuleNotFoundError as e:
        raise LookupError(f"Language not found: {language_name}") from e


def get_parser(language_name: SupportedLanguage) -> Parser:
    """Get a parser for the given language name."""
    return Parser(get_language(language_name=language_name))


__all__ = ["get_language", "get_parser", "SupportedLanguage"]
